# Generated by Django 6.0 on 2026-01-27 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remaining_life', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('win', 'Win'), ('lose', 'Lose')], default='ongoing', max_length=20)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='core.game')),
                ('deck', models.ManyToManyField(related_name='match_deck', to='core.occurrence')),
                ('player_hand', models.ManyToManyField(related_name='player_hand', to='core.occurrence')),
                ('timeline', models.ManyToManyField(related_name='timeline_occurrences', to='core.occurrence')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='deck',
            field=models.ManyToManyField(related_name='game_deck', to='core.occurrence'),
        ),
        migrations.AddField(
            model_name='game',
            name='starting_hand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_hand_card', to='core.occurrence'),
        ),
        migrations.AddField(
            model_name='game',
            name='starting_timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_board_card', to='core.occurrence'),
        ),
    ]
