# Generated by Django 6.0 on 2026-02-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_match_mistakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese')], default='en', max_length=20),
        ),
    ]
