# Generated by Django 6.0 on 2026-02-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='mistakes',
            field=models.ManyToManyField(related_name='mistakes', to='core.occurrence'),
        ),
    ]
